# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amrdoc',
            name='amr',
            field=models.TextField(blank=True),
        ),
    ]
